### ISSUE TITLE
Non-literal if-then-else arguments

### ISSUE THREAD

**Issue by AsFoxy** [SkaceKamen/sqflint#11]
if-then-else expects code literals.

```sqf
_then = {};

if true then _then;
```

**Comment by SkaceKamen** [comment]
This is by design.

**Comment by AsFoxy** [comment]
I see. SQF does accept any expression of type code though.

**Comment by SkaceKamen** [comment]
It does, it also accepts
```
_then = then {};
if true  _then;
```
I just choose to not allow this kind of stuff to provide better error checking.

**Comment by dedmen** [comment]
>It does, it also accepts
>_then = then {};
>if true  _then;

No it doesn't. `then` takes `IfType` on left side. What you wrote is syntax error.
This works
```
_ifStatement = if (true);
_thenElseCode = [{"then"},{"else"}];
_returnValue = _ifStatement then _thenElseCode;
```
Is the same as 
```
_returnValue = if (true) then {"then"} else {"else"}
```
