### ISSUE TITLE
Treat warnings as errors

### ISSUE THREAD

**Issue by Dahlgren** [SkaceKamen/sqflint#3]
An option to treat warnings as errors would be nice. Or an option to stop on warnings.

**Comment by SkaceKamen** [comment]
That shouldn't be big problem, but why?

**Comment by Dahlgren** [comment]
To fail CI builds on warnings :)

**Comment by SkaceKamen** [comment]
Makes sence

**Comment by SkaceKamen** [comment]
Warnings can now be treated as errors and you can now tell the CLI to return ERR(1) code when any error is encountered.

Note, that parser wont stop for warnings when this option is enabled, because warnings are built after parsing is complete.

**Comment by Dahlgren** [comment]
Awesome!
