### ISSUE TITLE
File with (only) comments throw lint error

### ISSUE THREAD

**Issue by pixlcrashr** [SkaceKamen/sqflint#7]
Hello.
You know what to do if you see the following image:
![unbenannt](https://cloud.githubusercontent.com/assets/10392626/24982271/f58de7e2-1fe0-11e7-835a-de476aa4f683.PNG)
Actually there is no real code above this.

**Comment by SkaceKamen** [comment]
I'll look into it

**Comment by SkaceKamen** [comment]
I'll release new version of vscode plugin with this fix shortly, after I fix some other issues.

**Comment by SkaceKamen** [comment]
It's released with 0.7.5
